export const projectListing = [
  {
    title: "Clayton Homes Retail Responsive Prototype",
    description:
      "Proof of concept to demonstrate a responsive version of the Clayton Home s retailer sites.",
    category: "Design/Development",
    slug: "/clayton-homes-retail",
    isFeatured: true,
    imageUrl: "/projects/clayton-retail.jpg",
    cta: "Launch Prototype",
  },
  {
    title: "React Component Library Case Study",
    description:
      "Check out this case study on a React component library I developed to make coding at Clayton Homes more consitent, inclusive, fast and efficient.",
    category: "Design Systems and React Development",
    slug: "/react-component-library",
    isFeatured: true,
    imageUrl: "/projects/smokey.jpg",
    cta: "View Case Study",
  },
  {
    title: "Oregon Trail Games Logo & Business Cards",
    description:
      "This logo was created for a table top gaming store. It was used on their business cards, and on storefront signage.",
    category: "Design Systems and React Development",
    slug: "/oregon-trail-games",
    isFeatured: true,
    imageUrl: "/projects/oregontrail.jpg",
  },
  {
    title: "Electric Vehicles 101 Infographic",
    description:
      "I created this as a personal pet project to inform others of the benefits of EVs.",
    category: "Graphic Design",
    slug: "/electric-vehicles-infographic",
    isFeatured: true,
    imageUrl: "/projects/evs-101.jpg",
  },
  {
    title: "Drag and Drop Home Search Tool Prototype",
    description: null,
    category: "Development",
    slug: "/home-search-prototype",
    isFeatured: false,
    imageUrl: "/projects/homesearch.jpg",
  },
  {
    title: "Stylish Slice Website",
    description: null,
    category: "Design and Development",
    slug: "/stylish-slice",
    isFeatured: false,
    imageUrl: "/projects/stylish-slice.jpg",
  },
  {
    title: "Consumer Affairs Landing Page",
    description: null,
    category: "Development",
    slug: "/consumer-affairs-lp",
    isFeatured: false,
    imageUrl: "/projects/consumer-affairs.jpg",
  },
  {
    title: "Real Estate Print Flyer",
    description: null,
    category: "Graphic Design",
    slug: "/real-estate-flyer",
    isFeatured: false,
    imageUrl: null,
  },
  {
    title: "Festivus Party Invitation",
    description: null,
    category: "Graphic Design",
    slug: "/festivus-invitation",
    isFeatured: false,
    imageUrl: null,
  },
];
